// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMNFDV5tJ89yUCqbVmUUSviMpRNYoHXmQ',
    appId: '1:1002303400171:web:eb1db62311bdd2959cf6ae',
    messagingSenderId: '1002303400171',
    projectId: 'dosedash-6b1b4',
    authDomain: 'dosedash-6b1b4.firebaseapp.com',
    storageBucket: 'dosedash-6b1b4.appspot.com',
    measurementId: 'G-Q0GXMF5JHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUvSgVnE5Y9egV7YBsuLGAntiWa30x4xg',
    appId: '1:1002303400171:android:91a63754312540c19cf6ae',
    messagingSenderId: '1002303400171',
    projectId: 'dosedash-6b1b4',
    storageBucket: 'dosedash-6b1b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhlq-8DTGCXftzqGmxSchEzq6vx3-R1fQ',
    appId: '1:1002303400171:ios:5c160916af1889939cf6ae',
    messagingSenderId: '1002303400171',
    projectId: 'dosedash-6b1b4',
    storageBucket: 'dosedash-6b1b4.appspot.com',
    iosBundleId: 'com.example.ddpatient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhlq-8DTGCXftzqGmxSchEzq6vx3-R1fQ',
    appId: '1:1002303400171:ios:5c160916af1889939cf6ae',
    messagingSenderId: '1002303400171',
    projectId: 'dosedash-6b1b4',
    storageBucket: 'dosedash-6b1b4.appspot.com',
    iosBundleId: 'com.example.ddpatient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMNFDV5tJ89yUCqbVmUUSviMpRNYoHXmQ',
    appId: '1:1002303400171:web:af61f0aa202d08c29cf6ae',
    messagingSenderId: '1002303400171',
    projectId: 'dosedash-6b1b4',
    authDomain: 'dosedash-6b1b4.firebaseapp.com',
    storageBucket: 'dosedash-6b1b4.appspot.com',
    measurementId: 'G-MTTEC54XZY',
  );
}
