// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOI8CNIJMjximuVLoqe2WzIDreNck4VBI',
    appId: '1:119828744488:web:2b6398a14ed9f4a0ede81d',
    messagingSenderId: '119828744488',
    projectId: 'dosedash-51e62',
    authDomain: 'dosedash-51e62.firebaseapp.com',
    storageBucket: 'dosedash-51e62.appspot.com',
    measurementId: 'G-BGTQKZVBFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL9IVwnpOPoJLqUGYBBOK73cLghaTr4is',
    appId: '1:119828744488:android:fcd8aeab03cb821bede81d',
    messagingSenderId: '119828744488',
    projectId: 'dosedash-51e62',
    storageBucket: 'dosedash-51e62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARpuAW8cRivVX-VT5LFxoMAgOYKy-w7mY',
    appId: '1:119828744488:ios:f73bf0096c79b011ede81d',
    messagingSenderId: '119828744488',
    projectId: 'dosedash-51e62',
    storageBucket: 'dosedash-51e62.appspot.com',
    iosBundleId: 'com.example.ddpatient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARpuAW8cRivVX-VT5LFxoMAgOYKy-w7mY',
    appId: '1:119828744488:ios:f73bf0096c79b011ede81d',
    messagingSenderId: '119828744488',
    projectId: 'dosedash-51e62',
    storageBucket: 'dosedash-51e62.appspot.com',
    iosBundleId: 'com.example.ddpatient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOI8CNIJMjximuVLoqe2WzIDreNck4VBI',
    appId: '1:119828744488:web:792ef78ef633950aede81d',
    messagingSenderId: '119828744488',
    projectId: 'dosedash-51e62',
    authDomain: 'dosedash-51e62.firebaseapp.com',
    storageBucket: 'dosedash-51e62.appspot.com',
    measurementId: 'G-JR77W3RZLQ',
  );
}
